### ISSUE TITLE
How to install a new runtime?

### ISSUE THREAD

**Issue by grahama1970** [Jonxslays/piston_rspy#11]
Hello. How do I install a new Python runtime with piston_rs? Thanks.

**Comment by Jonxslays** [comment]
Hello,

`piston_rs` and `piston_rspy` are just SDK's for interacting with the [Piston API](https://github.com/engineer-man/piston). They just make requests to whatever Piston instance you point to. There is no way to add new language runtimes via these libraries.

If you'd like to add support for a new runtime you have a couple options:

- Open an issue on the Piston repo requesting support for a particular language runtime and wait for them to add it.
- Open a pull request yourself on the Piston repo adding support for the new language runtime.
- Run you own instance of Piston where you are in full control of all the language runtimes.
